import React from "react";

export default function Hero() {
  return (
    <div className="mt-[100px]">
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
      Hero <br />
    </div>
  );
}
