import React from "react";
import SignUp from "../component/SignUp";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Daftar",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <SignUp />
    </>
  );
}
