import React from "react";
import SignIn from "../component/SignIn";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Daftar",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <SignIn />
    </>
  );
}
