import type { Metadata } from "next";
import "./globals.css";
import { myFontAlliance } from "./fonts";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "UMP Culinary | Platofrm UMKM Lokal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-baseWhite ${myFontAlliance.className}`}>
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
