import About from "@/app/component/About";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Tentang Kami",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <About />
    </>
  );
}
