import { Metadata } from "next";
import NavDashboard from "../component/NavDashboard";
import Sidebar from "../component/Sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
      <div className="block md:hidden">
        <NavDashboard />
      </div>
      <div className="hidden lg:block w-full flex-none md:w-64">
        <Sidebar />
      </div>
      <div className="flex-grow px-5 md:px-8 py-4 md:overflow-y-auto">
        {children}
      </div>
    </div>
  );
}
