import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Kedai",
  description: "Generated by create next app",
};

export default function page() {
  return <div>Kedai</div>;
}
